title:             Setia Blogs
email:             setiadeepanshu@gmail.com
description:       Setia Blogs
author:            Deepanshu Setia
baseurl:           "/setiablogs.github.io/"
url:               "http://setiablogs.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
